// Code generated by tools/sync-catalog/generate.mjs from tools/sync-catalog/manifest.json. DO NOT EDIT.

import { eq } from 'drizzle-orm'
import type { AccountSyncData, CategorySyncData, DebtorSyncData, DebtOperationSyncData, PlannedPaymentSyncData, TransactionSyncData, SyncOperationData } from '@trata/api'
import type { DbLike, EntityRow, SyncRowPatch } from './sync-data'
import type { AccountRow, CategoryRow, DebtorRow, DebtOperationRow, PlannedPaymentRow, TransactionRow } from '../schema'
import { accounts, categories, debtors, debtOperations, plannedPayments, transactions } from '../schema'

export const CATALOG_SYNC_ENTITY_IDS = ['account', 'category', 'debtor', 'debt_operation', 'planned_payment', 'transaction'] as const

export type CatalogSyncEntity = (typeof CATALOG_SYNC_ENTITY_IDS)[number]

function asString(value: unknown): string | null {
  return typeof value === 'string' ? value : null
}

function asNonEmpty(value: unknown): string | null {
  const normalized = asString(value)
  return normalized !== null && normalized.length > 0 ? normalized : null
}

function asInt(value: unknown): number | null {
  return typeof value === 'number' && Number.isSafeInteger(value) ? value : null
}

const CALENDAR_DAY_PATTERN = /^\d{4}-\d{2}-\d{2}$/

function asCalendarDay(value: unknown): string | null {
  return typeof value === 'string' && CALENDAR_DAY_PATTERN.test(value) ? value : null
}

const ACCOUNT_CURRENCY_VALUES = new Set(["USD", "EUR", "RUB"])
const CATEGORY_TYPE_VALUES = new Set(["income", "expense"])
const DEBT_OPERATION_DIRECTION_VALUES = new Set(["receivable", "payable"])
const DEBT_OPERATION_KIND_VALUES = new Set(["debt", "repayment"])
const PLANNED_PAYMENT_TYPE_VALUES = new Set(["expense", "income"])
const PLANNED_PAYMENT_REGULARITY_VALUES = new Set(["daily", "weekly", "monthly", "yearly"])
const PLANNED_PAYMENT_CONFIRMMODE_VALUES = new Set(["manual", "auto"])
const PLANNED_PAYMENT_REMINDER_VALUES = new Set(["off", "day_before", "on_day"])
const TRANSACTION_TYPE_VALUES = new Set(["income", "expense", "transfer", "adjustment"])

type DecodeOk<T> = { ok: true; payload: T }
type DecodeFail = { ok: false; field?: string }
export type CatalogRestoreDecodeResult<T> = DecodeOk<T> | DecodeFail

function ok<T>(payload: T): DecodeOk<T> {
  return { ok: true, payload }
}

function fail(field?: string): DecodeFail {
  return { ok: false, field }
}

export function readCatalogEntityRow(
  db: DbLike,
  entity: CatalogSyncEntity,
  id: string,
): EntityRow | undefined {
  switch (entity) {
    case 'account':
      return db.select().from(accounts).where(eq(accounts.id, id)).get()
    case 'category':
      return db.select().from(categories).where(eq(categories.id, id)).get()
    case 'debtor':
      return db.select().from(debtors).where(eq(debtors.id, id)).get()
    case 'debt_operation':
      return db.select().from(debtOperations).where(eq(debtOperations.id, id)).get()
    case 'planned_payment':
      return db.select().from(plannedPayments).where(eq(plannedPayments.id, id)).get()
    case 'transaction':
      return db.select().from(transactions).where(eq(transactions.id, id)).get()
  }
}

export function rowToCatalogPayload(
  entity: CatalogSyncEntity,
  row: EntityRow,
): Record<string, unknown> {
  switch (entity) {
    case 'account': {
      const typedRow = row as AccountRow
      return { id: typedRow.id, name: typedRow.name, currency: typedRow.currency, openingBalance: typedRow.openingBalance }
    }
    case 'category': {
      const typedRow = row as CategoryRow
      return { id: typedRow.id, name: typedRow.name, type: typedRow.type, icon: typedRow.icon, color: typedRow.color, archivedAt: typedRow.archivedAt }
    }
    case 'debtor': {
      const typedRow = row as DebtorRow
      return { id: typedRow.id, name: typedRow.name, note: typedRow.note }
    }
    case 'debt_operation': {
      const typedRow = row as DebtOperationRow
      return { id: typedRow.id, debtorId: typedRow.debtorId, direction: typedRow.direction, kind: typedRow.kind, amount: typedRow.amount, note: typedRow.note, occurredAt: typedRow.occurredAt }
    }
    case 'planned_payment': {
      const typedRow = row as PlannedPaymentRow
      return { id: typedRow.id, type: typedRow.type, amount: typedRow.amount, name: typedRow.name, accountId: typedRow.accountId, categoryId: typedRow.categoryId, nextDue: typedRow.nextDue, anchorDate: typedRow.anchorDate, regularity: typedRow.regularity, confirmMode: typedRow.confirmMode, reminder: typedRow.reminder, note: typedRow.note, version: typedRow.version }
    }
    case 'transaction': {
      const typedRow = row as TransactionRow
      if (typedRow.type === 'transfer') {
        return { id: typedRow.id, type: typedRow.type, amount: typedRow.amount, description: typedRow.description, occurredAt: typedRow.occurredAt, fromAccountId: typedRow.fromAccountId, toAccountId: typedRow.toAccountId }
      } else {
        return { id: typedRow.id, type: typedRow.type, amount: typedRow.amount, description: typedRow.description, occurredAt: typedRow.occurredAt, accountId: typedRow.accountId, categoryId: typedRow.categoryId }
      }
    }
  }
  return {}
}

export function payloadToCatalogSyncData(
  entity: CatalogSyncEntity,
  payload: Record<string, unknown>,
): SyncOperationData | null {
  switch (entity) {
    case 'account': {
      const currency = asString(payload.currency)
if (!currency || !ACCOUNT_CURRENCY_VALUES.has(currency)) return null
      const openingBalance = asInt(payload.openingBalance)
if (openingBalance === null) return null
      const data: AccountSyncData = {
        name: asString(payload.name) ?? "",
        currency: currency as AccountSyncData['currency'],
        openingBalance
      }
      return data.name ? data : null
    }
    case 'category': {
      const type = asString(payload.type)
if (!type || !CATEGORY_TYPE_VALUES.has(type)) return null
      const archivedAt = asString(payload.archivedAt)
      const data: CategorySyncData = {
        name: asString(payload.name) ?? "",
        type: type as CategorySyncData['type'],
        icon: asString(payload.icon) ?? "",
        color: asString(payload.color) ?? "",
        ...(archivedAt ? { archivedAt } : {})
      }
      return data.name && data.icon && data.color ? data : null
    }
    case 'debtor': {
      const data: DebtorSyncData = {
        name: asString(payload.name) ?? "",
        note: asString(payload.note) ?? ""
      }
      return data.name ? data : null
    }
    case 'debt_operation': {
      const debtorId = asString(payload.debtorId)
if (!debtorId) return null
      const direction = asString(payload.direction)
if (!direction || !DEBT_OPERATION_DIRECTION_VALUES.has(direction)) return null
      const kind = asString(payload.kind)
if (!kind || !DEBT_OPERATION_KIND_VALUES.has(kind)) return null
      const amount = asInt(payload.amount)
if (amount === null || amount < 1) return null
      const occurredAt = asString(payload.occurredAt)
if (!occurredAt) return null
      const data: DebtOperationSyncData = {
        debtorId,
        direction: direction as DebtOperationSyncData['direction'],
        kind: kind as DebtOperationSyncData['kind'],
        amount,
        note: asString(payload.note) ?? "",
        occurredAt
      }
      return data
    }
    case 'planned_payment': {
      const type = asString(payload.type)
if (!type || !PLANNED_PAYMENT_TYPE_VALUES.has(type)) return null
      const amount = asInt(payload.amount)
if (amount === null || amount < 1) return null
      const accountId = asString(payload.accountId)
if (!accountId) return null
      const categoryId = asString(payload.categoryId)
if (!categoryId) return null
      const nextDue = asCalendarDay(payload.nextDue)
if (!nextDue) return null
      const anchorDate = asCalendarDay(payload.anchorDate)
if (!anchorDate) return null
      const regularity = asString(payload.regularity)
if (!regularity || !PLANNED_PAYMENT_REGULARITY_VALUES.has(regularity)) return null
      const confirmMode = asString(payload.confirmMode)
if (!confirmMode || !PLANNED_PAYMENT_CONFIRMMODE_VALUES.has(confirmMode)) return null
      const reminder = asString(payload.reminder)
if (!reminder || !PLANNED_PAYMENT_REMINDER_VALUES.has(reminder)) return null
      const data: PlannedPaymentSyncData = {
        type: type as PlannedPaymentSyncData['type'],
        amount,
        name: asString(payload.name) ?? "",
        accountId,
        categoryId,
        nextDue,
        anchorDate,
        regularity: regularity as PlannedPaymentSyncData['regularity'],
        confirmMode: confirmMode as PlannedPaymentSyncData['confirmMode'],
        reminder: reminder as PlannedPaymentSyncData['reminder'],
        note: asString(payload.note) ?? ""
      }
      return data
    }
    case 'transaction': {
      const type = asString(payload.type)
if (!type || !TRANSACTION_TYPE_VALUES.has(type)) return null
      if (type === 'transfer') {
        const amount = asInt(payload.amount)
        if (amount === null || amount < 1) return null
        const occurredAt = asString(payload.occurredAt)
        if (!occurredAt) return null
        const fromAccountId = asString(payload.fromAccountId)
        if (!fromAccountId) return null
        const toAccountId = asString(payload.toAccountId)
        if (!toAccountId) return null
        return {
          type: type as TransactionSyncData['type'],
          amount,
          description: asString(payload.description) ?? "",
          occurredAt,
          fromAccountId,
          toAccountId
        }
      } else if (type === 'adjustment') {
        const amount = asInt(payload.amount)
        if (amount === null || amount === 0) return null
        const occurredAt = asString(payload.occurredAt)
        if (!occurredAt) return null
        const accountId = asString(payload.accountId)
        if (!accountId) return null
        return {
          type: type as TransactionSyncData['type'],
          amount,
          description: asString(payload.description) ?? "",
          occurredAt,
          accountId
        }
      } else {
        const amount = asInt(payload.amount)
        if (amount === null || amount < 1) return null
        const occurredAt = asString(payload.occurredAt)
        if (!occurredAt) return null
        const accountId = asString(payload.accountId)
        const categoryId = asString(payload.categoryId)
        if (!categoryId) return null
        return {
          type: type as TransactionSyncData['type'],
          amount,
          description: asString(payload.description) ?? "",
          occurredAt,
          accountId,
          categoryId
        }
      }
    }
  }
  return null
}

export function catalogSyncDataToRowPatch(
  entity: CatalogSyncEntity,
  payload: Record<string, unknown>,
): SyncRowPatch | null {
  switch (entity) {
    case 'account': {
      const currency = asString(payload.currency)
if (!currency || !ACCOUNT_CURRENCY_VALUES.has(currency)) return null
      const openingBalance = asInt(payload.openingBalance)
if (openingBalance === null) return null
      return {
        name: asString(payload.name) ?? "",
        currency,
        openingBalance
      }
    }
    case 'category': {
      const type = asString(payload.type)
if (!type || !CATEGORY_TYPE_VALUES.has(type)) return null
      const archivedAt = asString(payload.archivedAt)
      return {
        name: asString(payload.name) ?? "",
        type,
        icon: asString(payload.icon) ?? "",
        color: asString(payload.color) ?? "",
        archivedAt: asString(payload.archivedAt),
        slug: null
      }
    }
    case 'debtor': {
      return {
        name: asString(payload.name) ?? "",
        note: asString(payload.note) ?? ""
      }
    }
    case 'debt_operation': {
      const debtorId = asString(payload.debtorId)
if (!debtorId) return null
      const direction = asString(payload.direction)
if (!direction || !DEBT_OPERATION_DIRECTION_VALUES.has(direction)) return null
      const kind = asString(payload.kind)
if (!kind || !DEBT_OPERATION_KIND_VALUES.has(kind)) return null
      const amount = asInt(payload.amount)
if (amount === null || amount < 1) return null
      const occurredAt = asString(payload.occurredAt)
if (!occurredAt) return null
      return {
        debtorId,
        direction,
        kind,
        amount,
        note: asString(payload.note) ?? "",
        occurredAt
      }
    }
    case 'planned_payment': {
      const type = asString(payload.type)
if (!type || !PLANNED_PAYMENT_TYPE_VALUES.has(type)) return null
      const amount = asInt(payload.amount)
if (amount === null || amount < 1) return null
      const accountId = asString(payload.accountId)
if (!accountId) return null
      const categoryId = asString(payload.categoryId)
if (!categoryId) return null
      const nextDue = asCalendarDay(payload.nextDue)
if (!nextDue) return null
      const anchorDate = asCalendarDay(payload.anchorDate)
if (!anchorDate) return null
      const regularity = asString(payload.regularity)
if (!regularity || !PLANNED_PAYMENT_REGULARITY_VALUES.has(regularity)) return null
      const confirmMode = asString(payload.confirmMode)
if (!confirmMode || !PLANNED_PAYMENT_CONFIRMMODE_VALUES.has(confirmMode)) return null
      const reminder = asString(payload.reminder)
if (!reminder || !PLANNED_PAYMENT_REMINDER_VALUES.has(reminder)) return null
      return {
        type,
        amount,
        name: asString(payload.name) ?? "",
        accountId,
        categoryId,
        nextDue,
        anchorDate,
        regularity,
        confirmMode,
        reminder,
        note: asString(payload.note) ?? ""
      }
    }
    case 'transaction': {
      const type = asString(payload.type)
if (!type || !TRANSACTION_TYPE_VALUES.has(type)) return null
      if (type === 'transfer') {
        const amount = asInt(payload.amount)
        if (amount === null || amount < 1) return null
        const occurredAt = asString(payload.occurredAt)
        if (!occurredAt) return null
        const fromAccountId = asString(payload.fromAccountId)
        if (!fromAccountId) return null
        const toAccountId = asString(payload.toAccountId)
        if (!toAccountId) return null
        return {
          type,
          amount,
          description: asString(payload.description) ?? "",
          occurredAt,
          fromAccountId,
          toAccountId,
          accountId: null,
          categoryId: null
        }
      } else if (type === 'adjustment') {
        const amount = asInt(payload.amount)
        if (amount === null || amount === 0) return null
        const occurredAt = asString(payload.occurredAt)
        if (!occurredAt) return null
        const accountId = asString(payload.accountId)
        if (!accountId) return null
        return {
          type,
          amount,
          description: asString(payload.description) ?? "",
          occurredAt,
          accountId,
          fromAccountId: null,
          toAccountId: null,
          categoryId: null
        }
      } else {
        const amount = asInt(payload.amount)
        if (amount === null || amount < 1) return null
        const occurredAt = asString(payload.occurredAt)
        if (!occurredAt) return null
        const accountId = asString(payload.accountId)
        const categoryId = asString(payload.categoryId)
        if (!categoryId) return null
        return {
          type,
          amount,
          description: asString(payload.description) ?? "",
          occurredAt,
          accountId,
          categoryId,
          fromAccountId: null,
          toAccountId: null
        }
      }
    }
  }
  return null
}

export function decodeCatalogRestorePayload(
  entity: CatalogSyncEntity,
  state: Record<string, unknown>,
): CatalogRestoreDecodeResult<unknown> {
  switch (entity) {
    case 'account': {
      const name = asNonEmpty(state.name)
if (!name) return fail('name')
      const currency = asString(state.currency)
if (!currency || !ACCOUNT_CURRENCY_VALUES.has(currency)) return fail('currency')
      const openingBalance = asInt(state.openingBalance)
if (openingBalance === null) return fail('openingBalance')
      return ok({
        name,
        currency,
        openingBalance
      })
    }
    case 'category': {
      const name = asNonEmpty(state.name)
if (!name) return fail('name')
      const type = asString(state.type)
if (!type || !CATEGORY_TYPE_VALUES.has(type)) return fail('type')
      const icon = asNonEmpty(state.icon)
if (!icon) return fail('icon')
      const color = asNonEmpty(state.color)
if (!color) return fail('color')
      return ok({
        name,
        type,
        icon,
        color
      })
    }
    case 'debtor': {
      const name = asNonEmpty(state.name)
if (!name) return fail('name')
      const note = asString(state.note) ?? undefined
      return ok({
        name,
        ...(note !== undefined ? { note } : {})
      })
    }
    case 'debt_operation': {
      const debtorId = asNonEmpty(state.debtorId)
if (!debtorId) return fail('debtorId')
      const direction = asString(state.direction)
if (!direction || !DEBT_OPERATION_DIRECTION_VALUES.has(direction)) return fail('direction')
      const kind = asString(state.kind)
if (!kind || !DEBT_OPERATION_KIND_VALUES.has(kind)) return fail('kind')
      const amount = asInt(state.amount)
if (amount === null || amount < 1) return fail('amount')
      const occurredAt = asNonEmpty(state.occurredAt)
if (!occurredAt) return fail('occurredAt')
      const note = asString(state.note) ?? undefined
      return ok({
        debtorId,
        direction,
        kind,
        amount,
        occurredAt,
        ...(note !== undefined ? { note } : {})
      })
    }
    case 'planned_payment': {
      const type = asString(state.type)
if (!type || !PLANNED_PAYMENT_TYPE_VALUES.has(type)) return fail('type')
      const amount = asInt(state.amount)
if (amount === null || amount < 1) return fail('amount')
      const accountId = asNonEmpty(state.accountId)
if (!accountId) return fail('accountId')
      const categoryId = asNonEmpty(state.categoryId)
if (!categoryId) return fail('categoryId')
      const nextDue = asString(state.nextDue)
if (!nextDue || !CALENDAR_DAY_PATTERN.test(nextDue)) return fail('nextDue')
      const regularity = asString(state.regularity)
if (!regularity || !PLANNED_PAYMENT_REGULARITY_VALUES.has(regularity)) return fail('regularity')
      const confirmMode = asString(state.confirmMode)
if (!confirmMode || !PLANNED_PAYMENT_CONFIRMMODE_VALUES.has(confirmMode)) return fail('confirmMode')
      const reminder = asString(state.reminder)
if (!reminder || !PLANNED_PAYMENT_REMINDER_VALUES.has(reminder)) return fail('reminder')
      const name = asString(state.name) ?? undefined
      const note = asString(state.note) ?? undefined
      return ok({
        type,
        amount,
        accountId,
        categoryId,
        nextDue,
        regularity,
        confirmMode,
        reminder,
        ...(name !== undefined ? { name } : {}),
        ...(note !== undefined ? { note } : {})
      })
    }
    case 'transaction': {
      const type = asString(state.type)
if (!type || !TRANSACTION_TYPE_VALUES.has(type)) return fail('type')
      if (type === 'transfer') {
        const amount = asInt(state.amount)
        if (amount === null || amount < 1) return fail('amount')
        const description = asString(state.description) ?? ""
        const occurredAt = asNonEmpty(state.occurredAt)
        if (!occurredAt) return fail('occurredAt')
        const fromAccountId = asNonEmpty(state.fromAccountId)
        if (!fromAccountId) return fail('fromAccountId')
        const toAccountId = asNonEmpty(state.toAccountId)
        if (!toAccountId) return fail('toAccountId')
        return ok({
          type,
          amount,
          description,
          occurredAt,
          fromAccountId,
          toAccountId
        })
      } else if (type === 'adjustment') {
        const amount = asInt(state.amount)
        if (amount === null || amount === 0) return fail('amount')
        const description = asString(state.description) ?? ""
        const occurredAt = asNonEmpty(state.occurredAt)
        if (!occurredAt) return fail('occurredAt')
        const accountId = asNonEmpty(state.accountId)
        if (!accountId) return fail('accountId')
        return ok({
          type,
          amount,
          description,
          occurredAt,
          accountId
        })
      } else {
        const amount = asInt(state.amount)
        if (amount === null || amount < 1) return fail('amount')
        const description = asString(state.description) ?? ""
        const occurredAt = asNonEmpty(state.occurredAt)
        if (!occurredAt) return fail('occurredAt')
        const accountId = asString(state.accountId)
        const categoryId = asNonEmpty(state.categoryId)
        if (!categoryId) return fail('categoryId')
        return ok({
          type,
          amount,
          description,
          occurredAt,
          accountId,
          categoryId
        })
      }
    }
  }
  return fail()
}

export function catalogConflictSubject(
  entity: CatalogSyncEntity,
  source: Record<string, unknown> | undefined,
): string {
  switch (entity) {
    case 'account': {
      const name = typeof source?.name === 'string' ? source.name : ''
      return name
    }
    case 'category': {
      const name = typeof source?.name === 'string' ? source.name : ''
      return name
    }
    case 'debtor': {
      const name = typeof source?.name === 'string' ? source.name : ''
      return name
    }
    case 'debt_operation': {
      const note = typeof source?.note === 'string' ? source.note : ''
      return note
    }
    case 'planned_payment': {
      const name = typeof source?.name === 'string' ? source.name : ''
      return name
    }
    case 'transaction': {
      const description = typeof source?.description === 'string' ? source.description : ''
      return description
    }
  }
  return ''
}
