#!/usr/bin/env node

import { execFileSync } from 'node:child_process'
import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const repoRoot = path.resolve(__dirname, '..', '..')
const manifestPath = path.join(__dirname, 'manifest.json')

const manifest = JSON.parse(await fs.readFile(manifestPath, 'utf8'))
const entities = manifest.entities

function header(source) {
  return `// Code generated by tools/sync-catalog/generate.mjs from ${source}. DO NOT EDIT.\n`
}

function tsArray(values) {
  return values.map((value) => `'${value}'`).join(', ')
}

function indent(text, spaces) {
  const pad = ' '.repeat(spaces)
  return text
    .split('\n')
    .map((line) => (line.length > 0 ? `${pad}${line}` : line))
    .join('\n')
}

function toConstName(entityId, fieldName) {
  return `${entityId}_${fieldName}_values`.replaceAll(/[^a-zA-Z0-9]+/g, '_').toUpperCase()
}

function isDiscriminated(def) {
  return Boolean(def?.discriminator)
}

/** Enum field defs of a field list plus its discriminator (if any). */
function enumFieldDefs(fields, discriminator) {
  const defs = (fields ?? []).filter((field) => field.kind === 'enum').map((field) => ({ name: field.name, values: field.values }))
  if (discriminator) defs.push({ name: discriminator.field, values: discriminator.values })
  return defs
}

function variantCondition(varName, matches) {
  return matches.map((match) => `${varName} === '${match}'`).join(' || ')
}

/** Field names of every variant, first-appearance order. */
function allVariantFieldNames(variants) {
  const names = []
  for (const variant of variants) {
    for (const field of variant.fields) {
      if (!names.includes(field.name)) names.push(field.name)
    }
  }
  return names
}

function uniqueBy(items, keyFn) {
  const seen = new Set()
  return items.filter((item) => {
    const key = keyFn(item)
    if (seen.has(key)) return false
    seen.add(key)
    return true
  })
}

function renderEnumSets() {
  return uniqueBy(
    entities.flatMap((entity) => [
      ...enumFieldDefs(entity.syncData.fields, entity.syncData.discriminator).map((field) => ({ entity, field })),
      ...enumFieldDefs(entity.restore.fields, entity.syncData.discriminator).map((field) => ({ entity, field })),
    ]),
    ({ entity, field }) => `${entity.id}:${field.name}`,
  )
    .map(({ entity, field }) => {
      const constName = toConstName(entity.id, field.name)
      return `const ${constName} = new Set([${field.values.map((value) => JSON.stringify(value)).join(', ')}])`
    })
    .join('\n')
}

function renderSyncFieldPrelude(entity, sourceName, field) {
  switch (field.kind) {
    case 'string':
      if (field.nonEmpty) {
        return `const ${field.name} = asString(${sourceName}.${field.name})\nif (!${field.name}) return null`
      }
      if (field.nullable) {
        return `const ${field.name} = asString(${sourceName}.${field.name})`
      }
      return ''
    case 'enum':
      return `const ${field.name} = asString(${sourceName}.${field.name})\nif (!${field.name} || !${toConstName(entity.id, field.name)}.has(${field.name})) return null`
    case 'int':
      if (field.nonzero) {
        return `const ${field.name} = asInt(${sourceName}.${field.name})\nif (${field.name} === null || ${field.name} === 0) return null`
      }
      if (field.min !== undefined) {
        return `const ${field.name} = asInt(${sourceName}.${field.name})\nif (${field.name} === null || ${field.name} < ${field.min}) return null`
      }
      return `const ${field.name} = asInt(${sourceName}.${field.name})\nif (${field.name} === null) return null`
    case 'optionalInt':
      return `const ${field.name} = asInt(${sourceName}.${field.name})\nif (${field.name} !== null && ${field.name} <= 0) return null`
    case 'optionalString':
      return `const ${field.name} = asString(${sourceName}.${field.name})`
    case 'calendarDay':
      return `const ${field.name} = asCalendarDay(${sourceName}.${field.name})\nif (!${field.name}) return null`
    default:
      return ''
  }
}

function renderSyncFieldAssignment(entity, sourceName, field) {
  switch (field.kind) {
    case 'string':
      if (field.nonEmpty || field.nullable) {
        return field.name
      }
      return `${field.name}: asString(${sourceName}.${field.name}) ?? ${JSON.stringify(field.default ?? '')}`
    case 'enum':
      return `${field.name}: ${field.name} as ${entity.syncData.type}['${field.name}']`
    case 'int':
      return field.name
    case 'optionalInt':
      return `...(${field.name} !== null ? { ${field.name} } : {})`
    case 'optionalString':
      return `...(${field.name} ? { ${field.name} } : {})`
    case 'calendarDay':
      return field.name
    default:
      throw new Error(`Unsupported syncData field kind: ${field.kind}`)
  }
}

function renderRowPatchAssignment(sourceName, field) {
  switch (field.kind) {
    case 'string':
      if (field.nonEmpty || field.nullable) {
        return field.name
      }
      return `${field.name}: asString(${sourceName}.${field.name}) ?? ${JSON.stringify(field.default ?? '')}`
    case 'enum':
      return `${field.name}`
    case 'int':
      return field.name
    case 'optionalInt':
      return field.name
    case 'optionalString':
      return `${field.name}: asString(${sourceName}.${field.name})`
    case 'calendarDay':
      return field.name
    default:
      throw new Error(`Unsupported rowPatch field kind: ${field.kind}`)
  }
}

function renderRestorePrelude(entity, field) {
  switch (field.kind) {
    case 'string':
      if (field.nonEmpty) {
        return `const ${field.name} = asNonEmpty(state.${field.name})\nif (!${field.name}) return fail('${field.name}')`
      }
      if (field.nullable) {
        return `const ${field.name} = asString(state.${field.name})`
      }
      return `const ${field.name} = asString(state.${field.name}) ?? ${JSON.stringify(field.default ?? '')}`
    case 'optionalString':
      return `const ${field.name} = asString(state.${field.name}) ?? undefined`
    case 'enum':
      return `const ${field.name} = asString(state.${field.name})\nif (!${field.name} || !${toConstName(entity.id, field.name)}.has(${field.name})) return fail('${field.name}')`
    case 'int':
      if (field.nonzero) {
        return `const ${field.name} = asInt(state.${field.name})\nif (${field.name} === null || ${field.name} === 0) return fail('${field.name}')`
      }
      if (field.min !== undefined) {
        return `const ${field.name} = asInt(state.${field.name})\nif (${field.name} === null || ${field.name} < ${field.min}) return fail('${field.name}')`
      }
      return `const ${field.name} = asInt(state.${field.name})\nif (${field.name} === null) return fail('${field.name}')`
    case 'optionalInt':
      return `const ${field.name} = state.${field.name} === undefined ? null : asInt(state.${field.name})\nif (${field.name} !== null && ${field.name} <= 0) return fail('${field.name}')`
    case 'calendarDay':
      return `const ${field.name} = asString(state.${field.name})\nif (!${field.name} || !CALENDAR_DAY_PATTERN.test(${field.name})) return fail('${field.name}')`
    default:
      throw new Error(`Unsupported restore field kind: ${field.kind}`)
  }
}

function renderRestorePayloadField(field) {
  if (field.kind === 'optionalString') {
    return `...(${field.name} !== undefined ? { ${field.name} } : {})`
  }
  if (field.kind === 'optionalInt') {
    return `...(${field.name} !== null ? { ${field.name} } : {})`
  }
  return field.name
}
/** One `if / else if / ... / else` chain over a discriminator. The LAST
 * variant is the else branch. `subject` is the expression the variant
 * values are compared against (a local const, or `typedRow.field`). */
function renderVariantChain(discriminator, variants, subject, renderBody) {
  const parts = []
  variants.forEach((variant, index) => {
    const opener =
      index === 0
        ? `if (${variantCondition(subject, variant.matches)}) {`
        : index === variants.length - 1
          ? '} else {'
          : `} else if (${variantCondition(subject, variant.matches)}) {`
    parts.push(opener)
    parts.push(indent(renderBody(variant), 2))
  })
  parts.push('}')
  return parts.join('\n')
}

function renderLocalDataTs() {
  const catalogIds = entities.map((entity) => entity.id)
  const rowTypeImports = [...new Set(entities.map((entity) => entity.row.rowType))].join(', ')
  const schemaValueImports = [...new Set(entities.map((entity) => entity.row.table))].join(', ')
  const apiTypeImports = [...new Set(entities.map((entity) => entity.syncData.type))].join(', ')
  const enumSets = renderEnumSets()
  const readCases = entities
    .map(
      (entity) => `    case '${entity.id}':\n      return db.select().from(${entity.row.table}).where(eq(${entity.row.table}.id, id)).get()`,
    )
    .join('\n')
  const rowCases = entities
    .map((entity) => {
      if (entity.row.payloadVariants) {
        const disc = entity.syncData.discriminator
        const base = [
          'id: typedRow.id',
          `${disc.field}: typedRow.${disc.field}`,
          ...entity.row.payloadFields.map((field) => `${field}: typedRow.${field}`),
        ]
        const chain = renderVariantChain(entity.syncData.discriminator, entity.row.payloadVariants, `typedRow.${entity.syncData.discriminator.field}`, (variant) => {
          const fields = variant.fields.map((field) => `${field}: typedRow.${field}`).join(', ')
          return `return { ${base.join(', ')}, ${fields} }`
        })
        return `    case '${entity.id}': {\n      const typedRow = row as ${entity.row.rowType}\n${indent(chain, 6)}\n    }`
      }
      const flatFields = entity.row.payloadFields
        .map((field) => `${field}: typedRow.${field}`)
        .join(', ')
      return `    case '${entity.id}': {\n      const typedRow = row as ${entity.row.rowType}\n      return { id: typedRow.id, ${flatFields} }\n    }`
    })
    .join('\n')
  const payloadCases = entities
    .map((entity) => {
      if (isDiscriminated(entity.syncData)) {
        const disc = entity.syncData.discriminator
        const discPrelude = `const ${disc.field} = asString(payload.${disc.field})\nif (!${disc.field} || !${toConstName(entity.id, disc.field)}.has(${disc.field})) return null`
        const chain = renderVariantChain(disc, entity.syncData.variants, disc.field, (variant) => {
          const prelude = variant.fields
            .map((field) => renderSyncFieldPrelude(entity, 'payload', field))
            .filter(Boolean)
            .join('\n')
          const assignments = [
            `${disc.field}: ${disc.field} as ${entity.syncData.type}['${disc.field}']`,
            ...variant.fields.map((field) => renderSyncFieldAssignment(entity, 'payload', field)),
          ].join(',\n')
          return `${prelude ? `${prelude}\n` : ''}return {\n${indent(assignments, 2)}\n}`
        })
        return `    case '${entity.id}': {\n      ${discPrelude}\n${indent(chain, 6)}\n    }`
      }
      const prelude = entity.syncData.fields
        .map((field) => renderSyncFieldPrelude(entity, 'payload', field))
        .filter(Boolean)
        .join('\n      ')
      const assignments = entity.syncData.fields
        .map((field) => renderSyncFieldAssignment(entity, 'payload', field))
        .join(',\n')
      const guard = entity.syncData.guard ? `${entity.syncData.guard} ? data : null` : 'data'
      return `    case '${entity.id}': {\n${prelude ? `      ${prelude}\n` : ''}      const data: ${entity.syncData.type} = {\n${indent(assignments, 8)}\n      }\n      return ${guard}\n    }`
    })
    .join('\n')
  const patchCases = entities
    .map((entity) => {
      if (isDiscriminated(entity.syncData)) {
        const disc = entity.syncData.discriminator
        const discPrelude = `const ${disc.field} = asString(payload.${disc.field})\nif (!${disc.field} || !${toConstName(entity.id, disc.field)}.has(${disc.field})) return null`
        const allFields = allVariantFieldNames(entity.syncData.variants)
        const chain = renderVariantChain(disc, entity.syncData.variants, disc.field, (variant) => {
          const own = new Set(variant.fields.map((field) => field.name))
          const prelude = variant.fields
            .map((field) => renderSyncFieldPrelude(entity, 'payload', field))
            .filter(Boolean)
            .join('\n')
          const assignments = [
            disc.field,
            ...variant.fields.map((field) => renderRowPatchAssignment('payload', field)),
            ...allFields.filter((name) => !own.has(name)).map((name) => `${name}: null`),
          ].join(',\n')
          return `${prelude ? `${prelude}\n` : ''}return {\n${indent(assignments, 2)}\n}`
        })
        return `    case '${entity.id}': {\n      ${discPrelude}\n${indent(chain, 6)}\n    }`
      }
      const prelude = entity.syncData.fields
        .map((field) => renderSyncFieldPrelude(entity, 'payload', field))
        .filter(Boolean)
        .join('\n      ')
      const assignments = [
        ...entity.syncData.fields.map((field) => renderRowPatchAssignment('payload', field)),
        ...((entity.row.extraPatchFields ?? []).map((field) => `${field.name}: ${field.literal}`)),
      ].join(',\n')
      return `    case '${entity.id}': {\n${prelude ? `      ${prelude}\n` : ''}      return {\n${indent(assignments, 8)}\n      }\n    }`
    })
    .join('\n')
  const decodeCases = entities
    .map((entity) => {
      if (entity.restore.variants) {
        const disc = entity.syncData.discriminator
        const discPrelude = `const ${disc.field} = asString(state.${disc.field})\nif (!${disc.field} || !${toConstName(entity.id, disc.field)}.has(${disc.field})) return fail('${disc.field}')`
        const chain = renderVariantChain(disc, entity.restore.variants, disc.field, (variant) => {
          const prelude = variant.fields
            .map((field) => renderRestorePrelude(entity, field))
            .filter(Boolean)
            .join('\n')
          const payloadFields = [disc.field, ...variant.fields.map(renderRestorePayloadField)].join(',\n')
          return `${prelude ? `${prelude}\n` : ''}return ok({\n${indent(payloadFields, 2)}\n})`
        })
        return `    case '${entity.id}': {\n      ${discPrelude}\n${indent(chain, 6)}\n    }`
      }
      const prelude = entity.restore.fields
        .map((field) => renderRestorePrelude(entity, field))
        .join('\n      ')
      const payloadFields = entity.restore.fields.map(renderRestorePayloadField).join(',\n')
      return `    case '${entity.id}': {\n      ${prelude}\n      return ok({\n${indent(payloadFields, 8)}\n      })\n    }`
    })
    .join('\n')
  const subjectCases = entities
    .map((entity) => {
      const declarations = entity.subjectFields
        .map((field) => `const ${field} = typeof source?.${field} === 'string' ? source.${field} : ''`)
        .join('\n      ')
      // No subject fields (e.g. debt operations lost their note) render as
      // an empty subject: the conflict UI falls back to the entity label.
      return `    case '${entity.id}': {\n      ${declarations}\n      return ${entity.subjectFields.join(' || ') || "''"}\n    }`
    })
    .join('\n')

  return `${header('tools/sync-catalog/manifest.json')}
import { eq } from 'drizzle-orm'
import type { ${apiTypeImports}, SyncOperationData } from '@trata/api'
import type { DbLike, EntityRow, SyncRowPatch } from './sync-data'
import type { ${rowTypeImports} } from '../schema'
import { ${schemaValueImports} } from '../schema'

export const CATALOG_SYNC_ENTITY_IDS = [${tsArray(catalogIds)}] as const

export type CatalogSyncEntity = (typeof CATALOG_SYNC_ENTITY_IDS)[number]

function asString(value: unknown): string | null {
  return typeof value === 'string' ? value : null
}

function asNonEmpty(value: unknown): string | null {
  const normalized = asString(value)
  return normalized !== null && normalized.length > 0 ? normalized : null
}

function asInt(value: unknown): number | null {
  return typeof value === 'number' && Number.isSafeInteger(value) ? value : null
}

const CALENDAR_DAY_PATTERN = /^\\d{4}-\\d{2}-\\d{2}$/

function asCalendarDay(value: unknown): string | null {
  return typeof value === 'string' && CALENDAR_DAY_PATTERN.test(value) ? value : null
}

${enumSets}

type DecodeOk<T> = { ok: true; payload: T }
type DecodeFail = { ok: false; field?: string }
export type CatalogRestoreDecodeResult<T> = DecodeOk<T> | DecodeFail

function ok<T>(payload: T): DecodeOk<T> {
  return { ok: true, payload }
}

function fail(field?: string): DecodeFail {
  return { ok: false, field }
}

export function readCatalogEntityRow(
  db: DbLike,
  entity: CatalogSyncEntity,
  id: string,
): EntityRow | undefined {
  switch (entity) {
${readCases}
  }
}

export function rowToCatalogPayload(
  entity: CatalogSyncEntity,
  row: EntityRow,
): Record<string, unknown> {
  switch (entity) {
${rowCases}
  }
  return {}
}

export function payloadToCatalogSyncData(
  entity: CatalogSyncEntity,
  payload: Record<string, unknown>,
): SyncOperationData | null {
  switch (entity) {
${payloadCases}
  }
  return null
}

export function catalogSyncDataToRowPatch(
  entity: CatalogSyncEntity,
  payload: Record<string, unknown>,
): SyncRowPatch | null {
  switch (entity) {
${patchCases}
  }
  return null
}

export function decodeCatalogRestorePayload(
  entity: CatalogSyncEntity,
  state: Record<string, unknown>,
): CatalogRestoreDecodeResult<unknown> {
  switch (entity) {
${decodeCases}
  }
  return fail()
}

export function catalogConflictSubject(
  entity: CatalogSyncEntity,
  source: Record<string, unknown> | undefined,
): string {
  switch (entity) {
${subjectCases}
  }
  return ''
}
`
}

function renderWebTs() {
  const ids = entities.map((entity) => entity.id)
  const cases = entities
    .map((entity) => `    case '${entity.id}':\n      return t('${entity.webConflictLabelKey}')`)
    .join('\n')
  return `${header('tools/sync-catalog/manifest.json')}
export type CatalogConflictTranslator = (key: string) => string

export type CatalogConflictEntity = ${ids.map((id) => `'${id}'`).join(' | ')}

export function catalogConflictEntityLabel(
  t: CatalogConflictTranslator,
  entity: CatalogConflictEntity,
): string {
  switch (entity) {
${cases}
  }
  return ''
}
`
}

function renderMobileTs() {
  const ids = entities.map((entity) => entity.id)
  const cases = entities
    .map((entity) => `    case '${entity.id}':\n      return ${JSON.stringify(entity.mobileConflictLabelRu)}`)
    .join('\n')
  return `${header('tools/sync-catalog/manifest.json')}
export type CatalogConflictEntity = ${ids.map((id) => `'${id}'`).join(' | ')}

export function catalogConflictEntityLabel(entity: CatalogConflictEntity): string {
  switch (entity) {
${cases}
  }
  return ''
}
`
}

function renderGo() {
  const cases = entities
    .map((entity) => `\tcase ${entity.goDomainConst}:\n\t\treturn ${JSON.stringify(entity.label)}`)
    .join('\n')
  const invalidCases = entities
    .map((entity) => `\tcase ${entity.goDomainConst}:\n\t\treturn ${JSON.stringify(entity.goInvalidDataMessage)}`)
    .join('\n')
  return `${header('tools/sync-catalog/manifest.json')}
package service

import "github.com/yurifa/trata/backend/internal/domain"

func catalogSyncEntityLabel(entity string) string {
\tswitch entity {
${cases}
\tdefault:
\t\treturn ""
\t}
}

func catalogSyncEntityInvalidDataMessage(entity string) string {
\tswitch entity {
${invalidCases}
\tdefault:
\t\treturn ""
\t}
}
`
}

const outputs = [
  [path.join(repoRoot, 'packages/local-data/src/sync/sync-entity-catalog.generated.ts'), renderLocalDataTs()],
  [path.join(repoRoot, 'apps/web/src/features/sync-conflicts/model/sync-entity-catalog.generated.ts'), renderWebTs()],
  [path.join(repoRoot, 'apps/mobile/src/features/sync-conflicts/model/sync-entity-catalog.generated.ts'), renderMobileTs()],
  [path.join(repoRoot, 'backend/internal/service/sync_entity_catalog.gen.go'), renderGo()],
]

// Committed artifacts must be canonical-formatter clean, or the drift gate
// and the repo's own format hooks fight the generator forever. Normalize
// each artifact with the formatter its area uses (oxfmt for app TS, gofmt
// for Go); packages/local-data has no formatter and the generator's own
// style is canonical there. Fail loud when a formatter is missing.
function normalize(file) {
  const rel = path.relative(repoRoot, file)
  if (file.endsWith('.go')) {
    execFileSync('gofmt', ['-w', rel], { cwd: repoRoot, stdio: 'pipe' })
    return
  }
  if (rel.startsWith('apps/')) {
    const app = rel.split(path.sep)[1]
    execFileSync(
      path.join('node_modules', '.bin', 'oxfmt'),
      ['-c', `apps/${app}/.oxfmtrc.json`, '--write', rel],
      { cwd: repoRoot, stdio: 'pipe' },
    )
  }
}

for (const [file, content] of outputs) {
  await fs.mkdir(path.dirname(file), { recursive: true })
  await fs.writeFile(file, content)
  normalize(file)
  console.log(`[sync-catalog:gen] wrote ${path.relative(repoRoot, file)}`)
}
