// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAccount = `-- name: CreateAccount :one

INSERT INTO accounts (id, household_id, user_id, name, currency, opening_balance)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING
    id,
    user_id,
    name,
    currency,
    opening_balance,
    opening_balance::bigint AS balance,
    created_at,
    updated_at,
    version
`

type CreateAccountParams struct {
	ID             uuid.UUID
	HouseholdID    uuid.UUID
	UserID         uuid.UUID
	Name           string
	Currency       string
	OpeningBalance int64
}

type CreateAccountRow struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	Name           string
	Currency       string
	OpeningBalance int64
	Balance        int64
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Version        int32
}

// accounts. Every query scopes by household_id (IDOR-safe: an access from
// outside the household returns "not found", never the row). user_id stays on
// the rows as authorship (stamped from the session on create). Balance is
// computed via the account_contributions view (opening + sum(signed)).
// Deletes are soft (deleted_at tombstone); every read path that feeds
// listings/summaries filters tombstones, while the *Any reads (sync + conflict
// classification) include them.
// id is the optional client-generated id (offline-first clients).
func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (CreateAccountRow, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.ID,
		arg.HouseholdID,
		arg.UserID,
		arg.Name,
		arg.Currency,
		arg.OpeningBalance,
	)
	var i CreateAccountRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Currency,
		&i.OpeningBalance,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getAccount = `-- name: GetAccount :one
SELECT
    id,
    user_id,
    name,
    currency,
    opening_balance,
    balance,
    created_at,
    updated_at,
    version
FROM account_with_balance
WHERE id = $1 AND household_id = $2 AND deleted_at IS NULL
`

type GetAccountParams struct {
	ID          uuid.UUID
	HouseholdID uuid.UUID
}

type GetAccountRow struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	Name           string
	Currency       string
	OpeningBalance int64
	Balance        int64
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Version        int32
}

func (q *Queries) GetAccount(ctx context.Context, arg GetAccountParams) (GetAccountRow, error) {
	row := q.db.QueryRow(ctx, getAccount, arg.ID, arg.HouseholdID)
	var i GetAccountRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Currency,
		&i.OpeningBalance,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getAccountAny = `-- name: GetAccountAny :one
SELECT
    id,
    user_id,
    name,
    currency,
    opening_balance,
    balance,
    created_at,
    updated_at,
    version,
    deleted_at
FROM account_with_balance
WHERE id = $1 AND household_id = $2
`

type GetAccountAnyParams struct {
	ID          uuid.UUID
	HouseholdID uuid.UUID
}

type GetAccountAnyRow struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	Name           string
	Currency       string
	OpeningBalance int64
	Balance        int64
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Version        int32
	DeletedAt      *time.Time
}

// Includes tombstoned rows; used by sync push (serverState / idempotent
// delete) and REST conflict classification.
func (q *Queries) GetAccountAny(ctx context.Context, arg GetAccountAnyParams) (GetAccountAnyRow, error) {
	row := q.db.QueryRow(ctx, getAccountAny, arg.ID, arg.HouseholdID)
	var i GetAccountAnyRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Currency,
		&i.OpeningBalance,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.DeletedAt,
	)
	return i, err
}

const getAccounts = `-- name: GetAccounts :many
SELECT
    id,
    user_id,
    name,
    currency,
    opening_balance,
    balance,
    created_at,
    updated_at,
    version
FROM account_with_balance
WHERE household_id = $1 AND deleted_at IS NULL
ORDER BY created_at, id
`

type GetAccountsRow struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	Name           string
	Currency       string
	OpeningBalance int64
	Balance        int64
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Version        int32
}

func (q *Queries) GetAccounts(ctx context.Context, householdID uuid.UUID) ([]GetAccountsRow, error) {
	rows, err := q.db.Query(ctx, getAccounts, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAccountsRow
	for rows.Next() {
		var i GetAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Currency,
			&i.OpeningBalance,
			&i.Balance,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasLiveTransactionsForAccount = `-- name: HasLiveTransactionsForAccount :one
SELECT EXISTS(
    SELECT 1
    FROM transactions
    WHERE household_id = $1
      AND deleted_at IS NULL
      AND type <> 'adjustment'
      AND (account_id = $2 OR from_account_id = $2 OR to_account_id = $2)
) AS in_use
`

type HasLiveTransactionsForAccountParams struct {
	HouseholdID uuid.UUID
	AccountID   *uuid.UUID
}

// In-use guard for deletion: a non-deleted cashflow or transfer referencing
// the account blocks the tombstone. Adjustments never block - they are the
// account's own reconciliation bookkeeping and cascade with the delete
// (SoftDeleteAdjustmentsForAccount).
func (q *Queries) HasLiveTransactionsForAccount(ctx context.Context, arg HasLiveTransactionsForAccountParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasLiveTransactionsForAccount, arg.HouseholdID, arg.AccountID)
	var in_use bool
	err := row.Scan(&in_use)
	return in_use, err
}

const softDeleteAccount = `-- name: SoftDeleteAccount :one
UPDATE accounts
SET deleted_at = now(), version = version + 1, updated_at = now()
WHERE id = $1 AND household_id = $2 AND deleted_at IS NULL
RETURNING version
`

type SoftDeleteAccountParams struct {
	ID          uuid.UUID
	HouseholdID uuid.UUID
}

// Tombstone (never a hard DELETE): excluded from listings, retained for sync.
func (q *Queries) SoftDeleteAccount(ctx context.Context, arg SoftDeleteAccountParams) (int32, error) {
	row := q.db.QueryRow(ctx, softDeleteAccount, arg.ID, arg.HouseholdID)
	var version int32
	err := row.Scan(&version)
	return version, err
}

const softDeleteAdjustmentsForAccount = `-- name: SoftDeleteAdjustmentsForAccount :many
UPDATE transactions
SET deleted_at = now(), version = version + 1, updated_at = now()
WHERE household_id = $1 AND account_id = $2
  AND type = 'adjustment' AND deleted_at IS NULL
RETURNING id, version
`

type SoftDeleteAdjustmentsForAccountParams struct {
	HouseholdID uuid.UUID
	AccountID   *uuid.UUID
}

type SoftDeleteAdjustmentsForAccountRow struct {
	ID      uuid.UUID
	Version int32
}

// Cascade half of an account delete: tombstone the account's live
// adjustments (they reference no category and no second account, so they
// carry no meaning without it). Returns id+version per row for the
// per-record change_log appends.
func (q *Queries) SoftDeleteAdjustmentsForAccount(ctx context.Context, arg SoftDeleteAdjustmentsForAccountParams) ([]SoftDeleteAdjustmentsForAccountRow, error) {
	rows, err := q.db.Query(ctx, softDeleteAdjustmentsForAccount, arg.HouseholdID, arg.AccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SoftDeleteAdjustmentsForAccountRow
	for rows.Next() {
		var i SoftDeleteAdjustmentsForAccountRow
		if err := rows.Scan(&i.ID, &i.Version); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const syncAccountsByIDs = `-- name: SyncAccountsByIDs :many
SELECT
    id,
    user_id,
    name,
    currency,
    opening_balance,
    created_at,
    updated_at,
    version,
    deleted_at
FROM accounts
WHERE household_id = $1 AND id = ANY($2::uuid[])
`

type SyncAccountsByIDsParams struct {
	HouseholdID uuid.UUID
	Ids         []uuid.UUID
}

type SyncAccountsByIDsRow struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	Name           string
	Currency       string
	OpeningBalance int64
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Version        int32
	DeletedAt      *time.Time
}

// Batch fetch for pull data (current state of records named by change rows).
func (q *Queries) SyncAccountsByIDs(ctx context.Context, arg SyncAccountsByIDsParams) ([]SyncAccountsByIDsRow, error) {
	rows, err := q.db.Query(ctx, syncAccountsByIDs, arg.HouseholdID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SyncAccountsByIDsRow
	for rows.Next() {
		var i SyncAccountsByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Currency,
			&i.OpeningBalance,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const syncReplaceAccount = `-- name: SyncReplaceAccount :one
WITH updated AS (
    UPDATE accounts
    SET
        name            = $1,
        currency        = $2,
        opening_balance = $3,
        version         = version + 1,
        updated_at        = now()
    WHERE accounts.id = $4 AND accounts.household_id = $5
      AND accounts.deleted_at IS NULL AND accounts.version = $6
    RETURNING
        accounts.id,
        accounts.user_id,
        accounts.name,
        accounts.currency,
        accounts.opening_balance,
        accounts.created_at,
        accounts.updated_at,
        accounts.version
)
SELECT
    u.id,
    u.user_id,
    u.name,
    u.currency,
    u.opening_balance,
    v.balance,
    u.created_at,
    u.updated_at,
    u.version
FROM updated u
JOIN account_with_balance v ON v.id = u.id
`

type SyncReplaceAccountParams struct {
	Name           string
	Currency       string
	OpeningBalance int64
	ID             uuid.UUID
	HouseholdID    uuid.UUID
	BaseVersion    int32
}

type SyncReplaceAccountRow struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	Name           string
	Currency       string
	OpeningBalance int64
	Balance        int64
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Version        int32
}

// Full-state CAS upsert from a sync push: applies only on the exact base
// version of a live row; version increments by one. Post-update balance via
// the CTE join on account_with_balance (RETURNING cannot join).
func (q *Queries) SyncReplaceAccount(ctx context.Context, arg SyncReplaceAccountParams) (SyncReplaceAccountRow, error) {
	row := q.db.QueryRow(ctx, syncReplaceAccount,
		arg.Name,
		arg.Currency,
		arg.OpeningBalance,
		arg.ID,
		arg.HouseholdID,
		arg.BaseVersion,
	)
	var i SyncReplaceAccountRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Currency,
		&i.OpeningBalance,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const updateAccount = `-- name: UpdateAccount :one
WITH updated AS (
    UPDATE accounts
    SET
        name       = COALESCE($1, name),
        version    = version + 1,
        updated_at        = now()
    WHERE accounts.id = $2 AND accounts.household_id = $3
      AND accounts.deleted_at IS NULL AND accounts.version = $4
    RETURNING
        accounts.id,
        accounts.user_id,
        accounts.name,
        accounts.currency,
        accounts.opening_balance,
        accounts.created_at,
        accounts.updated_at,
        accounts.version
)
SELECT
    u.id,
    u.user_id,
    u.name,
    u.currency,
    u.opening_balance,
    v.balance,
    u.created_at,
    u.updated_at,
    u.version
FROM updated u
JOIN account_with_balance v ON v.id = u.id
`

type UpdateAccountParams struct {
	Name        *string
	ID          uuid.UUID
	HouseholdID uuid.UUID
	Version     int32
}

type UpdateAccountRow struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	Name           string
	Currency       string
	OpeningBalance int64
	Balance        int64
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Version        int32
}

// Optimistic concurrency: the WHERE clause includes version = @version (and
// liveness) so a concurrent update yields zero rows. COALESCE keeps a column
// unchanged when its narg is NULL (PATCH semantics). The post-update balance
// comes from account_with_balance via the CTE (RETURNING cannot join).
func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (UpdateAccountRow, error) {
	row := q.db.QueryRow(ctx, updateAccount,
		arg.Name,
		arg.ID,
		arg.HouseholdID,
		arg.Version,
	)
	var i UpdateAccountRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Currency,
		&i.OpeningBalance,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}
