// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: debtors.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createDebtor = `-- name: CreateDebtor :one

INSERT INTO debtors (id, household_id, user_id, name, currency)
VALUES (
    $1, $2, $3, $4,
    COALESCE($5::text, (SELECT currency FROM households WHERE id = $2))
)
RETURNING id, user_id, name, currency, created_at, updated_at, version
`

type CreateDebtorParams struct {
	ID          uuid.UUID
	HouseholdID uuid.UUID
	UserID      uuid.UUID
	Name        string
	Currency    *string
}

type CreateDebtorRow struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Name      string
	Currency  string
	CreatedAt time.Time
	UpdatedAt time.Time
	Version   int32
}

// debtors (household-scoped, unique name among LIVE rows only - the partial
// unique index ignores tombstones so a deleted name can be recreated). Scoped
// by household_id everywhere; user_id stays on rows as authorship; deletes
// are soft (deleted_at tombstone).
// id is the optional client-generated id (offline-first clients). currency
// falls back to the household's base currency when the client omits it.
func (q *Queries) CreateDebtor(ctx context.Context, arg CreateDebtorParams) (CreateDebtorRow, error) {
	row := q.db.QueryRow(ctx, createDebtor,
		arg.ID,
		arg.HouseholdID,
		arg.UserID,
		arg.Name,
		arg.Currency,
	)
	var i CreateDebtorRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const debtorNameTaken = `-- name: DebtorNameTaken :one
SELECT EXISTS(
    SELECT 1
    FROM debtors
    WHERE household_id = $1 AND name = $2 AND deleted_at IS NULL AND id <> $3
) AS taken
`

type DebtorNameTakenParams struct {
	HouseholdID uuid.UUID
	Name        string
	ExceptID    uuid.UUID
}

// Live-name uniqueness pre-check (race-free under the per-household
// change-log advisory lock); used by the sync path where a constraint
// violation would abort the shared batch transaction.
func (q *Queries) DebtorNameTaken(ctx context.Context, arg DebtorNameTakenParams) (bool, error) {
	row := q.db.QueryRow(ctx, debtorNameTaken, arg.HouseholdID, arg.Name, arg.ExceptID)
	var taken bool
	err := row.Scan(&taken)
	return taken, err
}

const getDebtor = `-- name: GetDebtor :one
SELECT id, user_id, name, currency, created_at, updated_at, version
FROM debtors
WHERE id = $1 AND household_id = $2 AND deleted_at IS NULL
`

type GetDebtorParams struct {
	ID          uuid.UUID
	HouseholdID uuid.UUID
}

type GetDebtorRow struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Name      string
	Currency  string
	CreatedAt time.Time
	UpdatedAt time.Time
	Version   int32
}

func (q *Queries) GetDebtor(ctx context.Context, arg GetDebtorParams) (GetDebtorRow, error) {
	row := q.db.QueryRow(ctx, getDebtor, arg.ID, arg.HouseholdID)
	var i GetDebtorRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getDebtorAny = `-- name: GetDebtorAny :one
SELECT id, user_id, name, currency, created_at, updated_at, version, deleted_at
FROM debtors
WHERE id = $1 AND household_id = $2
`

type GetDebtorAnyParams struct {
	ID          uuid.UUID
	HouseholdID uuid.UUID
}

type GetDebtorAnyRow struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Name      string
	Currency  string
	CreatedAt time.Time
	UpdatedAt time.Time
	Version   int32
	DeletedAt *time.Time
}

// Includes tombstoned rows (sync push + conflict classification).
func (q *Queries) GetDebtorAny(ctx context.Context, arg GetDebtorAnyParams) (GetDebtorAnyRow, error) {
	row := q.db.QueryRow(ctx, getDebtorAny, arg.ID, arg.HouseholdID)
	var i GetDebtorAnyRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.DeletedAt,
	)
	return i, err
}

const getDebtors = `-- name: GetDebtors :many
SELECT id, user_id, name, currency, created_at, updated_at, version
FROM debtors
WHERE household_id = $1 AND deleted_at IS NULL
ORDER BY created_at, id
`

type GetDebtorsRow struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Name      string
	Currency  string
	CreatedAt time.Time
	UpdatedAt time.Time
	Version   int32
}

func (q *Queries) GetDebtors(ctx context.Context, householdID uuid.UUID) ([]GetDebtorsRow, error) {
	rows, err := q.db.Query(ctx, getDebtors, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDebtorsRow
	for rows.Next() {
		var i GetDebtorsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Currency,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockDebtorForDelete = `-- name: LockDebtorForDelete :one
SELECT deleted_at
FROM debtors
WHERE id = $1 AND household_id = $2
FOR UPDATE
`

type LockDebtorForDeleteParams struct {
	ID          uuid.UUID
	HouseholdID uuid.UUID
}

// Row lock for the cascade delete: FOR UPDATE pins the debtor row against
// concurrent mutations for the rest of the transaction, and the deleted_at
// read classifies a tombstone (deleted = not-found) before any dependant is
// touched.
func (q *Queries) LockDebtorForDelete(ctx context.Context, arg LockDebtorForDeleteParams) (*time.Time, error) {
	row := q.db.QueryRow(ctx, lockDebtorForDelete, arg.ID, arg.HouseholdID)
	var deleted_at *time.Time
	err := row.Scan(&deleted_at)
	return deleted_at, err
}

const softDeleteDebtor = `-- name: SoftDeleteDebtor :one
UPDATE debtors
SET deleted_at = now(), version = version + 1, updated_at = now()
WHERE id = $1 AND household_id = $2 AND deleted_at IS NULL
RETURNING version
`

type SoftDeleteDebtorParams struct {
	ID          uuid.UUID
	HouseholdID uuid.UUID
}

func (q *Queries) SoftDeleteDebtor(ctx context.Context, arg SoftDeleteDebtorParams) (int32, error) {
	row := q.db.QueryRow(ctx, softDeleteDebtor, arg.ID, arg.HouseholdID)
	var version int32
	err := row.Scan(&version)
	return version, err
}

const syncDebtorsByIDs = `-- name: SyncDebtorsByIDs :many
SELECT id, user_id, name, currency, version, deleted_at
FROM debtors
WHERE household_id = $1 AND id = ANY($2::uuid[])
`

type SyncDebtorsByIDsParams struct {
	HouseholdID uuid.UUID
	Ids         []uuid.UUID
}

type SyncDebtorsByIDsRow struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Name      string
	Currency  string
	Version   int32
	DeletedAt *time.Time
}

func (q *Queries) SyncDebtorsByIDs(ctx context.Context, arg SyncDebtorsByIDsParams) ([]SyncDebtorsByIDsRow, error) {
	rows, err := q.db.Query(ctx, syncDebtorsByIDs, arg.HouseholdID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SyncDebtorsByIDsRow
	for rows.Next() {
		var i SyncDebtorsByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Currency,
			&i.Version,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const syncReplaceDebtor = `-- name: SyncReplaceDebtor :one
UPDATE debtors
SET
    name       = $1,
    version    = version + 1,
    updated_at = now()
WHERE id = $2 AND household_id = $3 AND deleted_at IS NULL AND version = $4
RETURNING id, user_id, name, currency, created_at, updated_at, version
`

type SyncReplaceDebtorParams struct {
	Name        string
	ID          uuid.UUID
	HouseholdID uuid.UUID
	BaseVersion int32
}

type SyncReplaceDebtorRow struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Name      string
	Currency  string
	CreatedAt time.Time
	UpdatedAt time.Time
	Version   int32
}

// Full-state CAS upsert from a sync push.
func (q *Queries) SyncReplaceDebtor(ctx context.Context, arg SyncReplaceDebtorParams) (SyncReplaceDebtorRow, error) {
	row := q.db.QueryRow(ctx, syncReplaceDebtor,
		arg.Name,
		arg.ID,
		arg.HouseholdID,
		arg.BaseVersion,
	)
	var i SyncReplaceDebtorRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const updateDebtor = `-- name: UpdateDebtor :one
UPDATE debtors
SET
    name       = COALESCE($1, name),
    version    = version + 1,
    updated_at = now()
WHERE id = $2 AND household_id = $3 AND deleted_at IS NULL AND version = $4
RETURNING id, user_id, name, currency, created_at, updated_at, version
`

type UpdateDebtorParams struct {
	Name        *string
	ID          uuid.UUID
	HouseholdID uuid.UUID
	Version     int32
}

type UpdateDebtorRow struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Name      string
	Currency  string
	CreatedAt time.Time
	UpdatedAt time.Time
	Version   int32
}

// Optimistic concurrency: the WHERE clause includes version = @version (and
// liveness) so a concurrent update yields zero rows. The name is the only
// updatable field; PATCH uses COALESCE for nil = keep (the service rejects a
// no-op before the write).
func (q *Queries) UpdateDebtor(ctx context.Context, arg UpdateDebtorParams) (UpdateDebtorRow, error) {
	row := q.db.QueryRow(ctx, updateDebtor,
		arg.Name,
		arg.ID,
		arg.HouseholdID,
		arg.Version,
	)
	var i UpdateDebtorRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}
