// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: debt_operations.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createDebtOperation = `-- name: CreateDebtOperation :one

INSERT INTO debt_operations (id, household_id, user_id, debtor_id, direction, kind, amount, occurred_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, debtor_id, direction, kind, amount, occurred_at, created_at, updated_at, version
`

type CreateDebtOperationParams struct {
	ID          uuid.UUID
	HouseholdID uuid.UUID
	UserID      uuid.UUID
	DebtorID    uuid.UUID
	Direction   string
	Kind        string
	Amount      int64
	OccurredAt  time.Time
}

type CreateDebtOperationRow struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	DebtorID   uuid.UUID
	Direction  string
	Kind       string
	Amount     int64
	OccurredAt time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Version    int32
}

// debt_operations (household-scoped ledger records referencing a debtor;
// direction and kind are immutable, amount is a positive int64 in minor
// units). user_id stays on rows as authorship. Deletes are soft (deleted_at
// tombstone); balances are derived from the live operation history, never
// stored.
// id is the optional client-generated id (offline-first clients).
func (q *Queries) CreateDebtOperation(ctx context.Context, arg CreateDebtOperationParams) (CreateDebtOperationRow, error) {
	row := q.db.QueryRow(ctx, createDebtOperation,
		arg.ID,
		arg.HouseholdID,
		arg.UserID,
		arg.DebtorID,
		arg.Direction,
		arg.Kind,
		arg.Amount,
		arg.OccurredAt,
	)
	var i CreateDebtOperationRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DebtorID,
		&i.Direction,
		&i.Kind,
		&i.Amount,
		&i.OccurredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getDebtOperation = `-- name: GetDebtOperation :one
SELECT id, user_id, debtor_id, direction, kind, amount, occurred_at, created_at, updated_at, version
FROM debt_operations
WHERE id = $1 AND household_id = $2 AND deleted_at IS NULL
`

type GetDebtOperationParams struct {
	ID          uuid.UUID
	HouseholdID uuid.UUID
}

type GetDebtOperationRow struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	DebtorID   uuid.UUID
	Direction  string
	Kind       string
	Amount     int64
	OccurredAt time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Version    int32
}

func (q *Queries) GetDebtOperation(ctx context.Context, arg GetDebtOperationParams) (GetDebtOperationRow, error) {
	row := q.db.QueryRow(ctx, getDebtOperation, arg.ID, arg.HouseholdID)
	var i GetDebtOperationRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DebtorID,
		&i.Direction,
		&i.Kind,
		&i.Amount,
		&i.OccurredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getDebtOperationAny = `-- name: GetDebtOperationAny :one
SELECT id, user_id, debtor_id, direction, kind, amount, occurred_at, created_at, updated_at, version, deleted_at
FROM debt_operations
WHERE id = $1 AND household_id = $2
`

type GetDebtOperationAnyParams struct {
	ID          uuid.UUID
	HouseholdID uuid.UUID
}

type GetDebtOperationAnyRow struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	DebtorID   uuid.UUID
	Direction  string
	Kind       string
	Amount     int64
	OccurredAt time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Version    int32
	DeletedAt  *time.Time
}

// Includes tombstoned rows (sync push + conflict classification).
func (q *Queries) GetDebtOperationAny(ctx context.Context, arg GetDebtOperationAnyParams) (GetDebtOperationAnyRow, error) {
	row := q.db.QueryRow(ctx, getDebtOperationAny, arg.ID, arg.HouseholdID)
	var i GetDebtOperationAnyRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DebtorID,
		&i.Direction,
		&i.Kind,
		&i.Amount,
		&i.OccurredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.DeletedAt,
	)
	return i, err
}

const getDebtOperations = `-- name: GetDebtOperations :many
SELECT id, user_id, debtor_id, direction, kind, amount, occurred_at, created_at, updated_at, version
FROM debt_operations
WHERE
    household_id = $1
    AND deleted_at IS NULL
    AND ($2::uuid IS NULL OR debtor_id = $2)
ORDER BY occurred_at DESC, id DESC
`

type GetDebtOperationsParams struct {
	HouseholdID uuid.UUID
	DebtorID    *uuid.UUID
}

type GetDebtOperationsRow struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	DebtorID   uuid.UUID
	Direction  string
	Kind       string
	Amount     int64
	OccurredAt time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Version    int32
}

func (q *Queries) GetDebtOperations(ctx context.Context, arg GetDebtOperationsParams) ([]GetDebtOperationsRow, error) {
	rows, err := q.db.Query(ctx, getDebtOperations, arg.HouseholdID, arg.DebtorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDebtOperationsRow
	for rows.Next() {
		var i GetDebtOperationsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DebtorID,
			&i.Direction,
			&i.Kind,
			&i.Amount,
			&i.OccurredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteDebtOperation = `-- name: SoftDeleteDebtOperation :one
UPDATE debt_operations
SET deleted_at = now(), version = version + 1, updated_at = now()
WHERE id = $1 AND household_id = $2 AND deleted_at IS NULL
RETURNING version
`

type SoftDeleteDebtOperationParams struct {
	ID          uuid.UUID
	HouseholdID uuid.UUID
}

func (q *Queries) SoftDeleteDebtOperation(ctx context.Context, arg SoftDeleteDebtOperationParams) (int32, error) {
	row := q.db.QueryRow(ctx, softDeleteDebtOperation, arg.ID, arg.HouseholdID)
	var version int32
	err := row.Scan(&version)
	return version, err
}

const softDeleteDebtOperationsForDebtor = `-- name: SoftDeleteDebtOperationsForDebtor :many
UPDATE debt_operations
SET deleted_at = now(), version = version + 1, updated_at = now()
WHERE household_id = $1 AND debtor_id = $2 AND deleted_at IS NULL
RETURNING id, version
`

type SoftDeleteDebtOperationsForDebtorParams struct {
	HouseholdID uuid.UUID
	DebtorID    uuid.UUID
}

type SoftDeleteDebtOperationsForDebtorRow struct {
	ID      uuid.UUID
	Version int32
}

// Cascade half of a debtor delete: tombstone every live operation of the
// debtor (balances are derived from live operations, so they recompute
// implicitly). Returns id+version per row for the per-record change_log
// appends.
func (q *Queries) SoftDeleteDebtOperationsForDebtor(ctx context.Context, arg SoftDeleteDebtOperationsForDebtorParams) ([]SoftDeleteDebtOperationsForDebtorRow, error) {
	rows, err := q.db.Query(ctx, softDeleteDebtOperationsForDebtor, arg.HouseholdID, arg.DebtorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SoftDeleteDebtOperationsForDebtorRow
	for rows.Next() {
		var i SoftDeleteDebtOperationsForDebtorRow
		if err := rows.Scan(&i.ID, &i.Version); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const syncDebtOperationsByIDs = `-- name: SyncDebtOperationsByIDs :many
SELECT id, user_id, debtor_id, direction, kind, amount, occurred_at, version, deleted_at
FROM debt_operations
WHERE household_id = $1 AND id = ANY($2::uuid[])
`

type SyncDebtOperationsByIDsParams struct {
	HouseholdID uuid.UUID
	Ids         []uuid.UUID
}

type SyncDebtOperationsByIDsRow struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	DebtorID   uuid.UUID
	Direction  string
	Kind       string
	Amount     int64
	OccurredAt time.Time
	Version    int32
	DeletedAt  *time.Time
}

func (q *Queries) SyncDebtOperationsByIDs(ctx context.Context, arg SyncDebtOperationsByIDsParams) ([]SyncDebtOperationsByIDsRow, error) {
	rows, err := q.db.Query(ctx, syncDebtOperationsByIDs, arg.HouseholdID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SyncDebtOperationsByIDsRow
	for rows.Next() {
		var i SyncDebtOperationsByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DebtorID,
			&i.Direction,
			&i.Kind,
			&i.Amount,
			&i.OccurredAt,
			&i.Version,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const syncReplaceDebtOperation = `-- name: SyncReplaceDebtOperation :one
UPDATE debt_operations
SET
    debtor_id   = $1,
    direction   = $2,
    kind        = $3,
    amount      = $4,
    occurred_at = $5,
    version     = version + 1,
    updated_at  = now()
WHERE id = $6 AND household_id = $7 AND deleted_at IS NULL AND version = $8
RETURNING id, user_id, debtor_id, direction, kind, amount, occurred_at, created_at, updated_at, version
`

type SyncReplaceDebtOperationParams struct {
	DebtorID    uuid.UUID
	Direction   string
	Kind        string
	Amount      int64
	OccurredAt  time.Time
	ID          uuid.UUID
	HouseholdID uuid.UUID
	BaseVersion int32
}

type SyncReplaceDebtOperationRow struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	DebtorID   uuid.UUID
	Direction  string
	Kind       string
	Amount     int64
	OccurredAt time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Version    int32
}

// Full-state CAS upsert from a sync push.
func (q *Queries) SyncReplaceDebtOperation(ctx context.Context, arg SyncReplaceDebtOperationParams) (SyncReplaceDebtOperationRow, error) {
	row := q.db.QueryRow(ctx, syncReplaceDebtOperation,
		arg.DebtorID,
		arg.Direction,
		arg.Kind,
		arg.Amount,
		arg.OccurredAt,
		arg.ID,
		arg.HouseholdID,
		arg.BaseVersion,
	)
	var i SyncReplaceDebtOperationRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DebtorID,
		&i.Direction,
		&i.Kind,
		&i.Amount,
		&i.OccurredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const updateDebtOperation = `-- name: UpdateDebtOperation :one
UPDATE debt_operations
SET
    amount      = COALESCE($1, amount),
    occurred_at = COALESCE($2, occurred_at),
    version     = version + 1,
    updated_at  = now()
WHERE id = $3 AND household_id = $4 AND deleted_at IS NULL AND version = $5
RETURNING id, user_id, debtor_id, direction, kind, amount, occurred_at, created_at, updated_at, version
`

type UpdateDebtOperationParams struct {
	Amount      *int64
	OccurredAt  *time.Time
	ID          uuid.UUID
	HouseholdID uuid.UUID
	Version     int32
}

type UpdateDebtOperationRow struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	DebtorID   uuid.UUID
	Direction  string
	Kind       string
	Amount     int64
	OccurredAt time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Version    int32
}

// Optimistic concurrency: the WHERE clause includes version = @version (and
// liveness) so a concurrent update yields zero rows. PATCH fields use
// COALESCE for nil = keep.
func (q *Queries) UpdateDebtOperation(ctx context.Context, arg UpdateDebtOperationParams) (UpdateDebtOperationRow, error) {
	row := q.db.QueryRow(ctx, updateDebtOperation,
		arg.Amount,
		arg.OccurredAt,
		arg.ID,
		arg.HouseholdID,
		arg.Version,
	)
	var i UpdateDebtOperationRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DebtorID,
		&i.Direction,
		&i.Kind,
		&i.Amount,
		&i.OccurredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}
