// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: households.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getHouseholdByID = `-- name: GetHouseholdByID :one
SELECT id, name, currency, created_at
FROM households
WHERE id = $1
`

type GetHouseholdByIDRow struct {
	ID        uuid.UUID
	Name      *string
	Currency  string
	CreatedAt time.Time
}

func (q *Queries) GetHouseholdByID(ctx context.Context, id uuid.UUID) (GetHouseholdByIDRow, error) {
	row := q.db.QueryRow(ctx, getHouseholdByID, id)
	var i GetHouseholdByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}

const getHouseholdMembers = `-- name: GetHouseholdMembers :many
SELECT m.household_id, m.user_id, u.email, u.display_name, m.role, m.joined_at
FROM household_members m
JOIN users u ON u.id = m.user_id
WHERE m.household_id = $1
ORDER BY m.joined_at, m.user_id
`

type GetHouseholdMembersRow struct {
	HouseholdID uuid.UUID
	UserID      uuid.UUID
	Email       string
	DisplayName *string
	Role        string
	JoinedAt    time.Time
}

// Member listing for GET /api/household: joined with the user's email and
// display name (null = never set).
func (q *Queries) GetHouseholdMembers(ctx context.Context, householdID uuid.UUID) ([]GetHouseholdMembersRow, error) {
	rows, err := q.db.Query(ctx, getHouseholdMembers, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetHouseholdMembersRow
	for rows.Next() {
		var i GetHouseholdMembersRow
		if err := rows.Scan(
			&i.HouseholdID,
			&i.UserID,
			&i.Email,
			&i.DisplayName,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMembershipByUser = `-- name: GetMembershipByUser :one

SELECT household_id, user_id, role, joined_at
FROM household_members
WHERE user_id = $1
`

// households + membership. The household is the scoping unit of all shared
// records; membership is the access right. v1 guarantees at most one
// membership per user (unique index idx_household_members_user), so the
// by-user lookup below is the middleware's single-hop household resolution.
func (q *Queries) GetMembershipByUser(ctx context.Context, userID uuid.UUID) (HouseholdMember, error) {
	row := q.db.QueryRow(ctx, getMembershipByUser, userID)
	var i HouseholdMember
	err := row.Scan(
		&i.HouseholdID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}
