// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: push.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deletePushSubscription = `-- name: DeletePushSubscription :execrows
DELETE FROM push_subscriptions WHERE id = $1 AND user_id = $2
`

type DeletePushSubscriptionParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// Scoped to the owner: another user's subscription deletes zero rows and
// reads as not-found (nothing leaks).
func (q *Queries) DeletePushSubscription(ctx context.Context, arg DeletePushSubscriptionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePushSubscription, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePushSubscriptionByID = `-- name: DeletePushSubscriptionByID :exec
DELETE FROM push_subscriptions WHERE id = $1
`

// Pruning after the push service reports a subscription gone (410/404):
// markers cascade, the device simply re-registers if it ever returns.
func (q *Queries) DeletePushSubscriptionByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePushSubscriptionByID, id)
	return err
}

const duePushReminderCandidates = `-- name: DuePushReminderCandidates :many
SELECT
    p.id AS plan_id, p.name AS plan_name, p.type AS plan_type, p.amount AS plan_amount,
    p.reminder, p.confirm_mode, p.next_due AS occurrence_date,
    s.id AS subscription_id, s.endpoint, s.p256dh, s.auth, s.time_zone
FROM planned_payments p
JOIN household_members hm ON hm.household_id = p.household_id
JOIN push_subscriptions s ON s.user_id = hm.user_id
WHERE p.deleted_at IS NULL
  AND p.reminder <> 'off'
  AND NOT (p.reminder = 'on_day' AND p.next_due > $1)
  AND NOT EXISTS (
      SELECT 1 FROM push_reminders_sent m
      WHERE m.plan_id = p.id
        AND m.subscription_id = s.id
        AND m.occurrence_date = p.next_due
  )
`

type DuePushReminderCandidatesRow struct {
	PlanID         uuid.UUID
	PlanName       string
	PlanType       string
	PlanAmount     int64
	Reminder       string
	ConfirmMode    string
	OccurrenceDate time.Time
	SubscriptionID uuid.UUID
	Endpoint       string
	P256dh         string
	Auth           string
	TimeZone       string
}

// Live plans with reminders joined to EVERY member's subscription of the
// owning household (household parity), minus occurrences already sent and
// minus on_day occurrences already handled (auto-executed by the server or
// manually confirmed early - both advanced next_due past today). The
// 10:00-subscriber-local reminder instant is computed in Go (exact IANA
// math with embedded tzdata), not SQL, so a bad timezone row poisons at
// most its own send, never the whole sweep.
func (q *Queries) DuePushReminderCandidates(ctx context.Context, today time.Time) ([]DuePushReminderCandidatesRow, error) {
	rows, err := q.db.Query(ctx, duePushReminderCandidates, today)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DuePushReminderCandidatesRow
	for rows.Next() {
		var i DuePushReminderCandidatesRow
		if err := rows.Scan(
			&i.PlanID,
			&i.PlanName,
			&i.PlanType,
			&i.PlanAmount,
			&i.Reminder,
			&i.ConfirmMode,
			&i.OccurrenceDate,
			&i.SubscriptionID,
			&i.Endpoint,
			&i.P256dh,
			&i.Auth,
			&i.TimeZone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPushReminderSent = `-- name: InsertPushReminderSent :exec
INSERT INTO push_reminders_sent (plan_id, occurrence_date, subscription_id)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type InsertPushReminderSentParams struct {
	PlanID         uuid.UUID
	OccurrenceDate time.Time
	SubscriptionID uuid.UUID
}

// Written only after a successful send; the PK is the at-most-once guard.
func (q *Queries) InsertPushReminderSent(ctx context.Context, arg InsertPushReminderSentParams) error {
	_, err := q.db.Exec(ctx, insertPushReminderSent, arg.PlanID, arg.OccurrenceDate, arg.SubscriptionID)
	return err
}

const prunePushRemindersSent = `-- name: PrunePushRemindersSent :execrows
DELETE FROM push_reminders_sent WHERE occurrence_date < $1
`

// Markers only matter while their occurrence is the plan's current next_due
// (lookback is minutes); anything a week stale is dead weight.
func (q *Queries) PrunePushRemindersSent(ctx context.Context, cutoff time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, prunePushRemindersSent, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertPushSubscription = `-- name: UpsertPushSubscription :one

INSERT INTO push_subscriptions (user_id, endpoint, p256dh, auth, time_zone)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (endpoint) DO UPDATE SET
    p256dh    = EXCLUDED.p256dh,
    auth      = EXCLUDED.auth,
    time_zone = EXCLUDED.time_zone,
    updated_at = now()
RETURNING id, user_id, endpoint, p256dh, auth, time_zone, created_at, updated_at
`

type UpsertPushSubscriptionParams struct {
	UserID   uuid.UUID
	Endpoint string
	P256dh   string
	Auth     string
	TimeZone string
}

// push_subscriptions (web-push change, ADR-0004): per-device Web Push
// registrations. NOT a synced entity - no change_log, no tombstones; dead
// subscriptions are hard-deleted. Household parity: a plan's reminders go
// to every member's subscription (join through household_members).
// One row per endpoint: re-registration refreshes keys + timezone.
func (q *Queries) UpsertPushSubscription(ctx context.Context, arg UpsertPushSubscriptionParams) (PushSubscription, error) {
	row := q.db.QueryRow(ctx, upsertPushSubscription,
		arg.UserID,
		arg.Endpoint,
		arg.P256dh,
		arg.Auth,
		arg.TimeZone,
	)
	var i PushSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Endpoint,
		&i.P256dh,
		&i.Auth,
		&i.TimeZone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
