// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createTransaction = `-- name: CreateTransaction :one

INSERT INTO transactions (
    id, household_id, user_id, type, amount, description, occurred_at,
    account_id, category_id, from_account_id, to_account_id, destination_amount
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING
    id, user_id, type, amount, description, occurred_at,
    created_at, updated_at, version,
    account_id, category_id, from_account_id, to_account_id, destination_amount
`

type CreateTransactionParams struct {
	ID                uuid.UUID
	HouseholdID       uuid.UUID
	UserID            uuid.UUID
	Type              string
	Amount            int64
	Description       string
	OccurredAt        time.Time
	AccountID         *uuid.UUID
	CategoryID        *uuid.UUID
	FromAccountID     *uuid.UUID
	ToAccountID       *uuid.UUID
	DestinationAmount *int64
}

type CreateTransactionRow struct {
	ID                uuid.UUID
	UserID            uuid.UUID
	Type              string
	Amount            int64
	Description       string
	OccurredAt        time.Time
	CreatedAt         time.Time
	UpdatedAt         time.Time
	Version           int32
	AccountID         *uuid.UUID
	CategoryID        *uuid.UUID
	FromAccountID     *uuid.UUID
	ToAccountID       *uuid.UUID
	DestinationAmount *int64
}

// transactions. Scoped by household_id everywhere (IDOR protection); user_id
// stays on rows as authorship. Deletes are soft (deleted_at tombstone):
// balances (via the account_contributions view) and listings filter
// tombstones; the *Any reads include them for sync.
//
// The keyset-cursor index transactions(household_id, occurred_at DESC, id
// DESC) serves ListTransactions directly.
// id is the optional client-generated id (offline-first clients).
func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (CreateTransactionRow, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.ID,
		arg.HouseholdID,
		arg.UserID,
		arg.Type,
		arg.Amount,
		arg.Description,
		arg.OccurredAt,
		arg.AccountID,
		arg.CategoryID,
		arg.FromAccountID,
		arg.ToAccountID,
		arg.DestinationAmount,
	)
	var i CreateTransactionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Amount,
		&i.Description,
		&i.OccurredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.AccountID,
		&i.CategoryID,
		&i.FromAccountID,
		&i.ToAccountID,
		&i.DestinationAmount,
	)
	return i, err
}

const getTransaction = `-- name: GetTransaction :one
SELECT
    id, user_id, type, amount, description, occurred_at,
    created_at, updated_at, version,
    account_id, category_id, from_account_id, to_account_id, destination_amount
FROM transactions
WHERE id = $1 AND household_id = $2 AND deleted_at IS NULL
`

type GetTransactionParams struct {
	ID          uuid.UUID
	HouseholdID uuid.UUID
}

type GetTransactionRow struct {
	ID                uuid.UUID
	UserID            uuid.UUID
	Type              string
	Amount            int64
	Description       string
	OccurredAt        time.Time
	CreatedAt         time.Time
	UpdatedAt         time.Time
	Version           int32
	AccountID         *uuid.UUID
	CategoryID        *uuid.UUID
	FromAccountID     *uuid.UUID
	ToAccountID       *uuid.UUID
	DestinationAmount *int64
}

func (q *Queries) GetTransaction(ctx context.Context, arg GetTransactionParams) (GetTransactionRow, error) {
	row := q.db.QueryRow(ctx, getTransaction, arg.ID, arg.HouseholdID)
	var i GetTransactionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Amount,
		&i.Description,
		&i.OccurredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.AccountID,
		&i.CategoryID,
		&i.FromAccountID,
		&i.ToAccountID,
		&i.DestinationAmount,
	)
	return i, err
}

const getTransactionAny = `-- name: GetTransactionAny :one
SELECT
    id, user_id, type, amount, description, occurred_at,
    created_at, updated_at, version,
    account_id, category_id, from_account_id, to_account_id, destination_amount,
    deleted_at
FROM transactions
WHERE id = $1 AND household_id = $2
`

type GetTransactionAnyParams struct {
	ID          uuid.UUID
	HouseholdID uuid.UUID
}

type GetTransactionAnyRow struct {
	ID                uuid.UUID
	UserID            uuid.UUID
	Type              string
	Amount            int64
	Description       string
	OccurredAt        time.Time
	CreatedAt         time.Time
	UpdatedAt         time.Time
	Version           int32
	AccountID         *uuid.UUID
	CategoryID        *uuid.UUID
	FromAccountID     *uuid.UUID
	ToAccountID       *uuid.UUID
	DestinationAmount *int64
	DeletedAt         *time.Time
}

// Includes tombstoned rows (sync push + conflict classification).
func (q *Queries) GetTransactionAny(ctx context.Context, arg GetTransactionAnyParams) (GetTransactionAnyRow, error) {
	row := q.db.QueryRow(ctx, getTransactionAny, arg.ID, arg.HouseholdID)
	var i GetTransactionAnyRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Amount,
		&i.Description,
		&i.OccurredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.AccountID,
		&i.CategoryID,
		&i.FromAccountID,
		&i.ToAccountID,
		&i.DestinationAmount,
		&i.DeletedAt,
	)
	return i, err
}

const listTransactions = `-- name: ListTransactions :many
SELECT
    id, user_id, type, amount, description, occurred_at,
    created_at, updated_at, version,
    account_id, category_id, from_account_id, to_account_id, destination_amount
FROM transactions
WHERE
    household_id = $1
    AND deleted_at IS NULL
    AND ($2::text IS NULL OR type = $2)
    AND (
        $3::uuid IS NULL
        OR account_id = $3
        OR from_account_id = $3
        OR to_account_id = $3
    )
    AND ($4::uuid IS NULL OR category_id = $4)
    AND ($5::timestamptz IS NULL OR occurred_at >= $5)
    AND ($6::timestamptz IS NULL OR occurred_at <= $6)
    AND (
        $7::timestamptz IS NULL
        OR occurred_at < $7
        OR (occurred_at = $7 AND id < $8)
    )
ORDER BY occurred_at DESC, id DESC
LIMIT $9
`

type ListTransactionsParams struct {
	HouseholdID      uuid.UUID
	Type             *string
	AccountID        *uuid.UUID
	CategoryID       *uuid.UUID
	FromDate         *time.Time
	ToDate           *time.Time
	CursorOccurredAt *time.Time
	CursorID         *uuid.UUID
	Limit            int32
}

type ListTransactionsRow struct {
	ID                uuid.UUID
	UserID            uuid.UUID
	Type              string
	Amount            int64
	Description       string
	OccurredAt        time.Time
	CreatedAt         time.Time
	UpdatedAt         time.Time
	Version           int32
	AccountID         *uuid.UUID
	CategoryID        *uuid.UUID
	FromAccountID     *uuid.UUID
	ToAccountID       *uuid.UUID
	DestinationAmount *int64
}

// Keyset cursor pagination (occurred_at DESC, id DESC). Each optional filter is
// applied only when its narg is non-NULL. The account filter matches a
// transaction if ANY of its account refs (account_id / from / to) equals it,
// preserving the original OR-across-refs semantics.
func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]ListTransactionsRow, error) {
	rows, err := q.db.Query(ctx, listTransactions,
		arg.HouseholdID,
		arg.Type,
		arg.AccountID,
		arg.CategoryID,
		arg.FromDate,
		arg.ToDate,
		arg.CursorOccurredAt,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransactionsRow
	for rows.Next() {
		var i ListTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Amount,
			&i.Description,
			&i.OccurredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
			&i.AccountID,
			&i.CategoryID,
			&i.FromAccountID,
			&i.ToAccountID,
			&i.DestinationAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTransaction = `-- name: SoftDeleteTransaction :one
UPDATE transactions
SET deleted_at = now(), version = version + 1, updated_at = now()
WHERE id = $1 AND household_id = $2 AND deleted_at IS NULL
RETURNING version
`

type SoftDeleteTransactionParams struct {
	ID          uuid.UUID
	HouseholdID uuid.UUID
}

func (q *Queries) SoftDeleteTransaction(ctx context.Context, arg SoftDeleteTransactionParams) (int32, error) {
	row := q.db.QueryRow(ctx, softDeleteTransaction, arg.ID, arg.HouseholdID)
	var version int32
	err := row.Scan(&version)
	return version, err
}

const syncReplaceTransaction = `-- name: SyncReplaceTransaction :one
UPDATE transactions
SET
    amount          = $1,
    description     = $2,
    occurred_at     = $3,
    account_id      = $4,
    category_id     = $5,
    from_account_id = $6,
    to_account_id   = $7,
    destination_amount = $8,
    version         = version + 1,
    updated_at      = now()
WHERE id = $9 AND household_id = $10 AND deleted_at IS NULL AND version = $11
RETURNING
    id, user_id, type, amount, description, occurred_at,
    created_at, updated_at, version,
    account_id, category_id, from_account_id, to_account_id, destination_amount
`

type SyncReplaceTransactionParams struct {
	Amount            int64
	Description       string
	OccurredAt        time.Time
	AccountID         *uuid.UUID
	CategoryID        *uuid.UUID
	FromAccountID     *uuid.UUID
	ToAccountID       *uuid.UUID
	DestinationAmount *int64
	ID                uuid.UUID
	HouseholdID       uuid.UUID
	BaseVersion       int32
}

type SyncReplaceTransactionRow struct {
	ID                uuid.UUID
	UserID            uuid.UUID
	Type              string
	Amount            int64
	Description       string
	OccurredAt        time.Time
	CreatedAt         time.Time
	UpdatedAt         time.Time
	Version           int32
	AccountID         *uuid.UUID
	CategoryID        *uuid.UUID
	FromAccountID     *uuid.UUID
	ToAccountID       *uuid.UUID
	DestinationAmount *int64
}

// Full-state CAS upsert from a sync push. Type is immutable.
func (q *Queries) SyncReplaceTransaction(ctx context.Context, arg SyncReplaceTransactionParams) (SyncReplaceTransactionRow, error) {
	row := q.db.QueryRow(ctx, syncReplaceTransaction,
		arg.Amount,
		arg.Description,
		arg.OccurredAt,
		arg.AccountID,
		arg.CategoryID,
		arg.FromAccountID,
		arg.ToAccountID,
		arg.DestinationAmount,
		arg.ID,
		arg.HouseholdID,
		arg.BaseVersion,
	)
	var i SyncReplaceTransactionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Amount,
		&i.Description,
		&i.OccurredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.AccountID,
		&i.CategoryID,
		&i.FromAccountID,
		&i.ToAccountID,
		&i.DestinationAmount,
	)
	return i, err
}

const syncTransactionsByIDs = `-- name: SyncTransactionsByIDs :many
SELECT
    id, user_id, type, amount, description, occurred_at,
    created_at, updated_at, version,
    account_id, category_id, from_account_id, to_account_id, destination_amount,
    deleted_at
FROM transactions
WHERE household_id = $1 AND id = ANY($2::uuid[])
`

type SyncTransactionsByIDsParams struct {
	HouseholdID uuid.UUID
	Ids         []uuid.UUID
}

type SyncTransactionsByIDsRow struct {
	ID                uuid.UUID
	UserID            uuid.UUID
	Type              string
	Amount            int64
	Description       string
	OccurredAt        time.Time
	CreatedAt         time.Time
	UpdatedAt         time.Time
	Version           int32
	AccountID         *uuid.UUID
	CategoryID        *uuid.UUID
	FromAccountID     *uuid.UUID
	ToAccountID       *uuid.UUID
	DestinationAmount *int64
	DeletedAt         *time.Time
}

func (q *Queries) SyncTransactionsByIDs(ctx context.Context, arg SyncTransactionsByIDsParams) ([]SyncTransactionsByIDsRow, error) {
	rows, err := q.db.Query(ctx, syncTransactionsByIDs, arg.HouseholdID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SyncTransactionsByIDsRow
	for rows.Next() {
		var i SyncTransactionsByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Amount,
			&i.Description,
			&i.OccurredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
			&i.AccountID,
			&i.CategoryID,
			&i.FromAccountID,
			&i.ToAccountID,
			&i.DestinationAmount,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions
SET
    amount           = COALESCE($1, amount),
    description      = COALESCE($2, description),
    occurred_at      = COALESCE($3, occurred_at),
    account_id       = COALESCE($4, account_id),
    category_id      = COALESCE($5, category_id),
    from_account_id  = COALESCE($6, from_account_id),
    to_account_id    = COALESCE($7, to_account_id),
    destination_amount = COALESCE($8, destination_amount),
    version          = version + 1,
    updated_at       = now()
WHERE id = $9 AND household_id = $10 AND deleted_at IS NULL AND version = $11
RETURNING
    id, user_id, type, amount, description, occurred_at,
    created_at, updated_at, version,
    account_id, category_id, from_account_id, to_account_id, destination_amount
`

type UpdateTransactionParams struct {
	Amount            *int64
	Description       *string
	OccurredAt        *time.Time
	AccountID         *uuid.UUID
	CategoryID        *uuid.UUID
	FromAccountID     *uuid.UUID
	ToAccountID       *uuid.UUID
	DestinationAmount *int64
	ID                uuid.UUID
	HouseholdID       uuid.UUID
	Version           int32
}

type UpdateTransactionRow struct {
	ID                uuid.UUID
	UserID            uuid.UUID
	Type              string
	Amount            int64
	Description       string
	OccurredAt        time.Time
	CreatedAt         time.Time
	UpdatedAt         time.Time
	Version           int32
	AccountID         *uuid.UUID
	CategoryID        *uuid.UUID
	FromAccountID     *uuid.UUID
	ToAccountID       *uuid.UUID
	DestinationAmount *int64
}

// Optimistic concurrency: the WHERE clause includes version = @version (and
// liveness) so a concurrent update yields zero rows (-> version conflict).
// version is incremented atomically; PATCH fields use COALESCE for nil = keep.
func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (UpdateTransactionRow, error) {
	row := q.db.QueryRow(ctx, updateTransaction,
		arg.Amount,
		arg.Description,
		arg.OccurredAt,
		arg.AccountID,
		arg.CategoryID,
		arg.FromAccountID,
		arg.ToAccountID,
		arg.DestinationAmount,
		arg.ID,
		arg.HouseholdID,
		arg.Version,
	)
	var i UpdateTransactionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Amount,
		&i.Description,
		&i.OccurredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.AccountID,
		&i.CategoryID,
		&i.FromAccountID,
		&i.ToAccountID,
		&i.DestinationAmount,
	)
	return i, err
}
